import Head from 'next/head';
import { Inter } from 'next/font/google';
import { Todo } from '@/interfaces/todo.int';
import { useTodosQuery } from '@/queries/todos';
import AddTodoForm from '@/components/AddTodoForm';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
	const todos = useTodosQuery();

	const hasTodos = todos.data?.length > 0;

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			</Head>

			<main className={inter.className}>
				<h1>Todos</h1>

				<br />
				<AddTodoForm />
				<br />

				{todos.isLoading ? (
					<div>Loading...</div>
				) : (
					<ul>
						{hasTodos &&
							todos.data.map((todo: Todo) => (
								<li key={todo.id}>{todo.title}</li>
							))}
						{!hasTodos && <li>No todos yet</li>}
					</ul>
				)}
			</main>
		</>
	);
}
